spring:
  application:
    name: pichincha
  datasource:
    url: jdbc:h2:file:~/BaseDatos.sql;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
      javax:
        persistence:
          schema-generation
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
