DROP ALL OBJECTS;

CREATE TABLE person
(
    "PERSON_ID"      IDENTITY PRIMARY KEY,
    "NAME"           VARCHAR(128) NOT NULL,
    "GENDER"         VARCHAR(20),
    "AGE"            INT,
    "IDENTIFICATION" VARCHAR(12),
    "ADDRESS"        VARCHAR(128),
    "PHONE"          VARCHAR(10),
    PRIMARY KEY ("PERSON_ID")
);

CREATE TABLE client
(
    "CLIENT_ID" LONG PRIMARY KEY AUTO_INCREMENT,
    "PASSWORD"  VARCHAR(20),
    "STATUS"    BOOLEAN,
    "PERSON_ID" LONG,
    PRIMARY KEY ("CLIENT_ID"),
    CONSTRAINT FK_CLIENT_PERSON FOREIGN KEY ("PERSON_ID") REFERENCES person ("PERSON_ID")
);

CREATE TABLE account
(
    "ACCOUNT_ID"      LONG PRIMARY KEY AUTO_INCREMENT,
    "NUMBER_ACCOUNT"  VARCHAR(20),
    "TYPE"            VARCHAR(20),
    "STATUS"          BOOLEAN,
    "INITIAL_BALANCE" DOUBLE,
    "BALANCE"         DOUBLE,
    "CLIENT_ID"       LONG,
    PRIMARY KEY ("ACCOUNT_ID"),
    CONSTRAINT FK_ACCOUNT_CLIENT FOREIGN KEY ("CLIENT_ID") REFERENCES client ("CLIENT_ID")
);

CREATE TABLE movement
(
    "MOVEMENT_ID" LONG PRIMARY KEY AUTO_INCREMENT,
    "ACCOUNT_ID"  LONG,
    "TYPE"        VARCHAR(20),
    "DATE"        DATE,
    "BALANCE"     DOUBLE,
    "VALUE"       DOUBLE,
    PRIMARY KEY ("MOVEMENT_ID"),
    CONSTRAINT FK_MOVEMENT_ACCOUNT FOREIGN KEY ("ACCOUNT_ID") REFERENCES account ("ACCOUNT_ID")
);
